import type { Metadata } from "next";
import { Montserrat, Oxanium } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header";
import ThemeProvider from "@/app/components/themeProvider";

import { GET } from "@/app/api/db/route";
const modules = await GET();

// Need to type the response using schema

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Initialise fonts
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});



export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head >
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#000000" /> */}
      </head>
      <body className={`${montserrat.variable} ${oxanium.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header modules={modules} />
          {children}
          <footer>
          </footer>
        </ThemeProvider>
      </body>
    </html >
  );
}
